### ISSUE TITLE
Zach Goldberg is ruining Tech Apps

### ISSUE THREAD

**Issue by kennyftang** [RRTechApps/Faster-Than-Asteroids#8]
We need to make Tech Apps great again!
#IMPEACHZACH

**Comment by hellohighlow** [comment]
The Rebellion has begun down with the bougoiskenny up with the greenletariot

**Comment by hellohighlow** [comment]
( ͡° ͜ʖ ͡°)
( ͡° ͜ʖ ͡°)
( ͡° ͜ʖ ͡°)
( ͡° ͜ʖ ͡°)
( ͡° ͜ʖ ͡°)
( ͡° ͜ʖ ͡°)
( ͡° ͜ʖ ͡°)
( ͡° ͜ʖ ͡°)
( ͡° ͜ʖ ͡°)
